# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-sles12-products
# VERSION               0

FROM registry.mgr.suse.de/sles12
MAINTAINER Mihai Dinca: "mdinca@suse.com"


RUN zypper ar -f http://nu.novell.com/SUSE/Products/SLE-SERVER/12/x86_64/product/ "SLES 12 Pool"
RUN zypper ar -f http://nu.novell.com/SUSE/Updates/SLE-SERVER/12/x86_64/update/ "SLES 12 Updates"
RUN zypper ar -f http://nu.novell.com/SUSE/Products/SLE-SDK/12/x86_64/product/ "SLE-SDK 12 Pool"
RUN zypper ar -f http://nu.novell.com/SUSE/Updates/SLE-SDK/12/x86_64/update/ "SLE-SDK 12 Updates"
RUN zypper ar -f http://nu.novell.com/SUSE/Products/SLE-Manager-Tools/12/x86_64/product/ "SLE-Manager-Tools 12 Pool"
RUN zypper ar -f http://nu.novell.com/SUSE/Updates/SLE-Manager-Tools/12/x86_64/update/ "SLE-Manager-Tools 12 Updates"

RUN zypper ar -f http://download.suse.de/ibs/home:/mdinca:/base/SLE_12/ "salt"
RUN zypper mr -p 1 salt

RUN zypper --non-interactive --gpg-auto-import-keys ref

RUN zypper --non-interactive in salt-master salt-minion salt-proxy
